table_extraction_prompts:
  system_prompt: "You are a helpful AI assistant specialized in extracting table data from images."

table_transformer:
  model_name_hf: "microsoft/table-transformer-detection"
